version: "3.9"

services:
  postgres:
    image: postgres:15-alpine
    container_name: flightbooker-postgres
    environment:
      POSTGRES_USER: flightbooker
      POSTGRES_PASSWORD: flightbooker
      POSTGRES_DB: flightbooker
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U flightbooker"]
      interval: 5s
      timeout: 3s
      retries: 5

  localstack:
    image: localstack/localstack:3.4.0
    container_name: flightbooker-localstack
    environment:
      SERVICES: sqs
      DEFAULT_REGION: us-east-1
      DOCKER_HOST: unix:///var/run/docker.sock
    ports:
      - "4566:4566"
    volumes:
      - localstack_data:/var/lib/localstack
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4566/_localstack/health"]
      interval: 5s
      timeout: 3s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: flightbooker-redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  pgdata:
  localstack_data:
